# TODO: Add scheduled build jobs to this file
steps:
  - label: 'Benchmark'
    commands:
      - 'cd skeleton && nix-shell -p haskellPackages.niv --run "niv update iohk-nix -b $BUILDKITE_BRANCH"'  # TODO: remove this line
      - '.buildkite/bench.sh'
    timeout_in_minutes: 60
    branches: master
    agents:
      system: x86_64-linux
