# The Buildkite pipeline definition.
# See https://buildkite.com/docs/pipelines for documentation.

# The "cd skeleton" commands are here because this is in a subdirectory of
# iohk-nix.
# TODO: remove all the "cd skeleton" lines

env:
  BUILD_DIR: "/build/iohk-skeleton"
  STACK_ROOT: "/build/iohk-skeleton.stack"
  CACHE_DIR: "/cache/iohk-skeleton"

steps:
  # TODO: Remove this and define your own build steps.
  - label: Lint the fuzz
    commands:
      - 'cd skeleton && nix-shell -p haskellPackages.niv --run "niv update iohk-nix -b $BUILDKITE_BRANCH"'  # TODO: remove this line
      - "nix-build -A checks.lint-fuzz -o check-lint-fuzz.sh"
      - "./check-lint-fuzz.sh"
    agents:
      system: x86_64-linux

  - label: Check repo dependency tags are present on master branches
    commands:
      - 'cd skeleton && nix-shell -p haskellPackages.niv --run "niv update iohk-nix -b $BUILDKITE_BRANCH"'  # TODO: remove this line
      - "nix build -f ./nix iohkNix.checkRepoTagsOnMasterBranches --arg src ./. --show-trace"
    agents:
      system: x86_64-linux

  # Imperative build steps
  - label: Stack build
    commands:
      - 'cd skeleton && nix-shell -p haskellPackages.niv --run "niv update iohk-nix -b $BUILDKITE_BRANCH"'  # TODO: remove this line
      - "nix-build .buildkite/default.nix -o sr"
      - "./sr/bin/rebuild --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR"
    agents:
      system: x86_64-linux
    timeout_in_minutes: 60
    branches: master
    artifact_paths:
      - "/build/iohk-skeleton/.stack-work/logs/iohk-skeleton*.log"
